services:
  zend-3-app-2:
    build:
      args:
        user: lucas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lucazsilverio/zf3
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: unless-stopped
    networks:
      - docker-zend
            
  #nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8127:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-zend
  
  #mysql
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - 3339:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: zend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - docker-zend

networks:
  docker-zend:
    driver: bridge
